services:

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
    # ports:
    #   - "5432:5432"
    #   (HOST:CONTAINER)
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    container_name: nginx-container
    build: ./nginx
    restart: always
    ports:
      # - "8080:80"
      - "80:80"
    volumes:
      - api_data:/code
      - ./log:/var/log/nginx
      - ./my_htpasswd:/my_htpasswd
    depends_on:
      - api

  api:
    container_name: api-container
    build: ./api
    restart: always
    entrypoint: /code/docker-entrypoint.sh
    # command: uwsgi  --emperor uwsgi.ini
    # command: uwsgi --ini uwsgi.ini
    command: python manage.py runserver 0.0.0.0:8000

    # ref.
    # https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-createsuperuser
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin1234
      - DJANGO_SUPERUSER_EMAIL=admin@local.com

    ports:
      - "8000:8000"
    volumes:
      - api_data:/code
      - .:/workspace
    depends_on:
      - db
  # auto migrate django
  # migration:
  #     build: ./api
  #     command:
  #         - /bin/sh
  #         - -c
  #         - |
  #           python manage.py collectstatic --noinput
  #           python manage.py migrate
  #           python manage.py makemigrations musics
  #           python manage.py migrate
  #     volumes:
  #     - api_data:/code
  #     depends_on:
  #     - db

volumes:
  api_data:
  pgdata:
